// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.14.0
// source: api/pedant/pedant.proto

package pedant

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const ()

// PedantClient is the client API for Pedant service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PedantClient interface {
}

type pedantClient struct {
	cc grpc.ClientConnInterface
}

func NewPedantClient(cc grpc.ClientConnInterface) PedantClient {
	return &pedantClient{cc}
}

// PedantServer is the server API for Pedant service.
// All implementations must embed UnimplementedPedantServer
// for forward compatibility
type PedantServer interface {
	mustEmbedUnimplementedPedantServer()
}

// UnimplementedPedantServer must be embedded to have forward compatible implementations.
type UnimplementedPedantServer struct {
}

func (UnimplementedPedantServer) mustEmbedUnimplementedPedantServer() {}

// UnsafePedantServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PedantServer will
// result in compilation errors.
type UnsafePedantServer interface {
	mustEmbedUnimplementedPedantServer()
}

func RegisterPedantServer(s grpc.ServiceRegistrar, srv PedantServer) {
	s.RegisterService(&Pedant_ServiceDesc, srv)
}

// Pedant_ServiceDesc is the grpc.ServiceDesc for Pedant service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pedant_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pedant.pedant",
	HandlerType: (*PedantServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "api/pedant/pedant.proto",
}
